// Objective-C API for talking to github.com/hajimehoshi/rpgsnack-runtime/mobile Go package.
//   gobind -lang=objc github.com/hajimehoshi/rpgsnack-runtime/mobile
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_H__
#define __Mobile_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT BOOL MobileIsRunning();

FOUNDATION_EXPORT long MobileScreenHeight();

FOUNDATION_EXPORT long MobileScreenWidth();

FOUNDATION_EXPORT void MobileSetData(NSData* jsonData);

FOUNDATION_EXPORT BOOL MobileStart(double scale, NSError** error);

FOUNDATION_EXPORT BOOL MobileUpdate(NSError** error);

FOUNDATION_EXPORT void MobileUpdateTouchesOnAndroid(long action, long id_, long x, long y);

FOUNDATION_EXPORT void MobileUpdateTouchesOnIOS(long phase, int64_t ptr, long x, long y);

#endif
